# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend Production Deployment

on:
  push:
    branches: [ production ]
    paths:
    - "frontend/**"

jobs:
  integration-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      working-directory: frontend
      run: npm install
    - name: Run tests
      working-directory: frontend
      run: npm run test
    - name: Generate static HTML files
      working-directory: frontend
      run: npm run build --if-present

  deployment: 
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TESTSERVERHOST }}
        username: ${{ secrets.TESTSERVERUSER }}
        password: ${{ secrets.TESTSERVERPASS }}
        script: cd ocean/frontend && sh deploy.sh

